use serde::Serialize;
use tracing::info;

#[derive(Clone, Copy, Debug, Serialize)]
pub struct Move {
    pub id: u16,
    pub name: &'static str,
    pub move_type: &'static str,
    pub category: &'static str,
    pub pp: u16,
    pub power: Option<u16>,
    pub accuracy: Option<u16>,
}
pub const MOVES: &[Move] = &[
    Move {
        id: 1,
        name: "Pound",
        move_type: "Normal",
        category: "Physical",
        pp: 35,
        power: Some(40),
        accuracy: Some(100),
    },
    Move {
        id: 2,
        name: "Karate Chop",
        move_type: "Fighting",
        category: "Physical",
        pp: 25,
        power: Some(50),
        accuracy: Some(100),
    },
    Move {
        id: 3,
        name: "Double Slap",
        move_type: "Normal",
        category: "Physical",
        pp: 10,
        power: Some(15),
        accuracy: Some(85),
    },
    Move {
        id: 4,
        name: "Comet Punch",
        move_type: "Normal",
        category: "Physical",
        pp: 15,
        power: Some(18),
        accuracy: Some(85),
    },
    Move {
        id: 5,
        name: "Mega Punch",
        move_type: "Normal",
        category: "Physical",
        pp: 20,
        power: Some(80),
        accuracy: Some(85),
    },
    Move {
        id: 6,
        name: "Pay Day",
        move_type: "Normal",
        category: "Physical",
        pp: 20,
        power: Some(40),
        accuracy: Some(100),
    },
    Move {
        id: 7,
        name: "Fire Punch",
        move_type: "Fire",
        category: "Physical",
        pp: 15,
        power: Some(75),
        accuracy: Some(100),
    },
    Move {
        id: 8,
        name: "Ice Punch",
        move_type: "Ice",
        category: "Physical",
        pp: 15,
        power: Some(75),
        accuracy: Some(100),
    },
    Move {
        id: 9,
        name: "Thunder Punch",
        move_type: "Electric",
        category: "Physical",
        pp: 15,
        power: Some(75),
        accuracy: Some(100),
    },
    Move {
        id: 10,
        name: "Scratch",
        move_type: "Normal",
        category: "Physical",
        pp: 35,
        power: Some(40),
        accuracy: Some(100),
    },
    Move {
        id: 11,
        name: "Vise Grip",
        move_type: "Normal",
        category: "Physical",
        pp: 30,
        power: Some(55),
        accuracy: Some(100),
    },
    Move {
        id: 12,
        name: "Guillotine",
        move_type: "Normal",
        category: "Physical",
        pp: 5,
        power: None,
        accuracy: Some(30),
    },
    Move {
        id: 13,
        name: "Razor Wind",
        move_type: "Normal",
        category: "Special",
        pp: 10,
        power: Some(80),
        accuracy: Some(100),
    },
    Move {
        id: 14,
        name: "Swords Dance",
        move_type: "Normal",
        category: "Status",
        pp: 20,
        power: None,
        accuracy: None,
    },
    Move {
        id: 15,
        name: "Cut",
        move_type: "Normal",
        category: "Physical",
        pp: 30,
        power: Some(50),
        accuracy: Some(95),
    },
    Move {
        id: 16,
        name: "Gust",
        move_type: "Flying",
        category: "Special",
        pp: 35,
        power: Some(40),
        accuracy: Some(100),
    },
    Move {
        id: 17,
        name: "Wing Attack",
        move_type: "Flying",
        category: "Physical",
        pp: 35,
        power: Some(60),
        accuracy: Some(100),
    },
    Move {
        id: 18,
        name: "Whirlwind",
        move_type: "Normal",
        category: "Status",
        pp: 20,
        power: None,
        accuracy: None,
    },
    Move {
        id: 19,
        name: "Fly",
        move_type: "Flying",
        category: "Physical",
        pp: 15,
        power: Some(90),
        accuracy: Some(95),
    },
    Move {
        id: 20,
        name: "Bind",
        move_type: "Normal",
        category: "Physical",
        pp: 20,
        power: Some(15),
        accuracy: Some(85),
    },
    Move {
        id: 21,
        name: "Slam",
        move_type: "Normal",
        category: "Physical",
        pp: 20,
        power: Some(80),
        accuracy: Some(75),
    },
    Move {
        id: 22,
        name: "Vine Whip",
        move_type: "Grass",
        category: "Physical",
        pp: 25,
        power: Some(45),
        accuracy: Some(100),
    },
    Move {
        id: 23,
        name: "Stomp",
        move_type: "Normal",
        category: "Physical",
        pp: 20,
        power: Some(65),
        accuracy: Some(100),
    },
    Move {
        id: 24,
        name: "Double Kick",
        move_type: "Fighting",
        category: "Physical",
        pp: 30,
        power: Some(30),
        accuracy: Some(100),
    },
    Move {
        id: 25,
        name: "Mega Kick",
        move_type: "Normal",
        category: "Physical",
        pp: 5,
        power: Some(120),
        accuracy: Some(75),
    },
    Move {
        id: 26,
        name: "Jump Kick",
        move_type: "Fighting",
        category: "Physical",
        pp: 10,
        power: Some(100),
        accuracy: Some(95),
    },
    Move {
        id: 27,
        name: "Rolling Kick",
        move_type: "Fighting",
        category: "Physical",
        pp: 15,
        power: Some(60),
        accuracy: Some(85),
    },
    Move {
        id: 28,
        name: "Sand Attack",
        move_type: "Ground",
        category: "Status",
        pp: 15,
        power: None,
        accuracy: Some(100),
    },
    Move {
        id: 29,
        name: "Headbutt",
        move_type: "Normal",
        category: "Physical",
        pp: 15,
        power: Some(70),
        accuracy: Some(100),
    },
    Move {
        id: 30,
        name: "Horn Attack",
        move_type: "Normal",
        category: "Physical",
        pp: 25,
        power: Some(65),
        accuracy: Some(100),
    },
    Move {
        id: 31,
        name: "Fury Attack",
        move_type: "Normal",
        category: "Physical",
        pp: 20,
        power: Some(15),
        accuracy: Some(85),
    },
    Move {
        id: 32,
        name: "Horn Drill",
        move_type: "Normal",
        category: "Physical",
        pp: 5,
        power: None,
        accuracy: Some(30),
    },
    Move {
        id: 33,
        name: "Tackle",
        move_type: "Normal",
        category: "Physical",
        pp: 35,
        power: Some(40),
        accuracy: Some(100),
    },
    Move {
        id: 34,
        name: "Body Slam",
        move_type: "Normal",
        category: "Physical",
        pp: 15,
        power: Some(85),
        accuracy: Some(100),
    },
    Move {
        id: 35,
        name: "Wrap",
        move_type: "Normal",
        category: "Physical",
        pp: 20,
        power: Some(15),
        accuracy: Some(90),
    },
    Move {
        id: 36,
        name: "Take Down",
        move_type: "Normal",
        category: "Physical",
        pp: 20,
        power: Some(90),
        accuracy: Some(85),
    },
    Move {
        id: 37,
        name: "Thrash",
        move_type: "Normal",
        category: "Physical",
        pp: 10,
        power: Some(120),
        accuracy: Some(100),
    },
    Move {
        id: 38,
        name: "Double-Edge",
        move_type: "Normal",
        category: "Physical",
        pp: 15,
        power: Some(120),
        accuracy: Some(100),
    },
    Move {
        id: 39,
        name: "Tail Whip",
        move_type: "Normal",
        category: "Status",
        pp: 30,
        power: None,
        accuracy: Some(100),
    },
    Move {
        id: 40,
        name: "Poison Sting",
        move_type: "Poison",
        category: "Physical",
        pp: 35,
        power: Some(15),
        accuracy: Some(100),
    },
    Move {
        id: 41,
        name: "Twineedle",
        move_type: "Bug",
        category: "Physical",
        pp: 20,
        power: Some(25),
        accuracy: Some(100),
    },
    Move {
        id: 42,
        name: "Pin Missile",
        move_type: "Bug",
        category: "Physical",
        pp: 20,
        power: Some(25),
        accuracy: Some(95),
    },
    Move {
        id: 43,
        name: "Leer",
        move_type: "Normal",
        category: "Status",
        pp: 30,
        power: None,
        accuracy: Some(100),
    },
    Move {
        id: 44,
        name: "Bite",
        move_type: "Dark",
        category: "Physical",
        pp: 25,
        power: Some(60),
        accuracy: Some(100),
    },
    Move {
        id: 45,
        name: "Growl",
        move_type: "Normal",
        category: "Status",
        pp: 40,
        power: None,
        accuracy: Some(100),
    },
    Move {
        id: 46,
        name: "Roar",
        move_type: "Normal",
        category: "Status",
        pp: 20,
        power: None,
        accuracy: None,
    },
    Move {
        id: 47,
        name: "Sing",
        move_type: "Normal",
        category: "Status",
        pp: 15,
        power: None,
        accuracy: Some(55),
    },
    Move {
        id: 48,
        name: "Supersonic",
        move_type: "Normal",
        category: "Status",
        pp: 20,
        power: None,
        accuracy: Some(55),
    },
    Move {
        id: 49,
        name: "Sonic Boom",
        move_type: "Normal",
        category: "Special",
        pp: 20,
        power: None,
        accuracy: Some(90),
    },
    Move {
        id: 50,
        name: "Disable",
        move_type: "Normal",
        category: "Status",
        pp: 20,
        power: None,
        accuracy: Some(100),
    },
    Move {
        id: 51,
        name: "Acid",
        move_type: "Poison",
        category: "Special",
        pp: 30,
        power: Some(40),
        accuracy: Some(100),
    },
    Move {
        id: 52,
        name: "Ember",
        move_type: "Fire",
        category: "Special",
        pp: 25,
        power: Some(40),
        accuracy: Some(100),
    },
    Move {
        id: 53,
        name: "Flamethrower",
        move_type: "Fire",
        category: "Special",
        pp: 15,
        power: Some(90),
        accuracy: Some(100),
    },
    Move {
        id: 54,
        name: "Mist",
        move_type: "Ice",
        category: "Status",
        pp: 30,
        power: None,
        accuracy: None,
    },
    Move {
        id: 55,
        name: "Water Gun",
        move_type: "Water",
        category: "Special",
        pp: 25,
        power: Some(40),
        accuracy: Some(100),
    },
    Move {
        id: 56,
        name: "Hydro Pump",
        move_type: "Water",
        category: "Special",
        pp: 5,
        power: Some(110),
        accuracy: Some(80),
    },
    Move {
        id: 57,
        name: "Surf",
        move_type: "Water",
        category: "Special",
        pp: 15,
        power: Some(90),
        accuracy: Some(100),
    },
    Move {
        id: 58,
        name: "Ice Beam",
        move_type: "Ice",
        category: "Special",
        pp: 10,
        power: Some(90),
        accuracy: Some(100),
    },
    Move {
        id: 59,
        name: "Blizzard",
        move_type: "Ice",
        category: "Special",
        pp: 5,
        power: Some(110),
        accuracy: Some(70),
    },
    Move {
        id: 60,
        name: "Psybeam",
        move_type: "Psychic",
        category: "Special",
        pp: 20,
        power: Some(65),
        accuracy: Some(100),
    },
    Move {
        id: 61,
        name: "Bubble Beam",
        move_type: "Water",
        category: "Special",
        pp: 20,
        power: Some(65),
        accuracy: Some(100),
    },
    Move {
        id: 62,
        name: "Aurora Beam",
        move_type: "Ice",
        category: "Special",
        pp: 20,
        power: Some(65),
        accuracy: Some(100),
    },
    Move {
        id: 63,
        name: "Hyper Beam",
        move_type: "Normal",
        category: "Special",
        pp: 5,
        power: Some(150),
        accuracy: Some(90),
    },
    Move {
        id: 64,
        name: "Peck",
        move_type: "Flying",
        category: "Physical",
        pp: 35,
        power: Some(35),
        accuracy: Some(100),
    },
    Move {
        id: 65,
        name: "Drill Peck",
        move_type: "Flying",
        category: "Physical",
        pp: 20,
        power: Some(80),
        accuracy: Some(100),
    },
    Move {
        id: 66,
        name: "Submission",
        move_type: "Fighting",
        category: "Physical",
        pp: 20,
        power: Some(80),
        accuracy: Some(80),
    },
    Move {
        id: 67,
        name: "Low Kick",
        move_type: "Fighting",
        category: "Physical",
        pp: 20,
        power: None,
        accuracy: Some(100),
    },
    Move {
        id: 68,
        name: "Counter",
        move_type: "Fighting",
        category: "Physical",
        pp: 20,
        power: None,
        accuracy: Some(100),
    },
    Move {
        id: 69,
        name: "Seismic Toss",
        move_type: "Fighting",
        category: "Physical",
        pp: 20,
        power: None,
        accuracy: Some(100),
    },
    Move {
        id: 70,
        name: "Strength",
        move_type: "Normal",
        category: "Physical",
        pp: 15,
        power: Some(80),
        accuracy: Some(100),
    },
    Move {
        id: 71,
        name: "Absorb",
        move_type: "Grass",
        category: "Special",
        pp: 25,
        power: Some(20),
        accuracy: Some(100),
    },
    Move {
        id: 72,
        name: "Mega Drain",
        move_type: "Grass",
        category: "Special",
        pp: 15,
        power: Some(40),
        accuracy: Some(100),
    },
    Move {
        id: 73,
        name: "Leech Seed",
        move_type: "Grass",
        category: "Status",
        pp: 10,
        power: None,
        accuracy: Some(90),
    },
    Move {
        id: 74,
        name: "Growth",
        move_type: "Normal",
        category: "Status",
        pp: 20,
        power: None,
        accuracy: None,
    },
    Move {
        id: 75,
        name: "Razor Leaf",
        move_type: "Grass",
        category: "Physical",
        pp: 25,
        power: Some(55),
        accuracy: Some(95),
    },
    Move {
        id: 76,
        name: "Solar Beam",
        move_type: "Grass",
        category: "Special",
        pp: 10,
        power: Some(120),
        accuracy: Some(100),
    },
    Move {
        id: 77,
        name: "Poison Powder",
        move_type: "Poison",
        category: "Status",
        pp: 35,
        power: None,
        accuracy: Some(75),
    },
    Move {
        id: 78,
        name: "Stun Spore",
        move_type: "Grass",
        category: "Status",
        pp: 30,
        power: None,
        accuracy: Some(75),
    },
    Move {
        id: 79,
        name: "Sleep Powder",
        move_type: "Grass",
        category: "Status",
        pp: 15,
        power: None,
        accuracy: Some(75),
    },
    Move {
        id: 80,
        name: "Petal Dance",
        move_type: "Grass",
        category: "Special",
        pp: 10,
        power: Some(120),
        accuracy: Some(100),
    },
    Move {
        id: 81,
        name: "String Shot",
        move_type: "Bug",
        category: "Status",
        pp: 40,
        power: None,
        accuracy: Some(95),
    },
    Move {
        id: 82,
        name: "Dragon Rage",
        move_type: "Dragon",
        category: "Special",
        pp: 10,
        power: None,
        accuracy: Some(100),
    },
    Move {
        id: 83,
        name: "Fire Spin",
        move_type: "Fire",
        category: "Special",
        pp: 15,
        power: Some(35),
        accuracy: Some(85),
    },
    Move {
        id: 84,
        name: "Thunder Shock",
        move_type: "Electric",
        category: "Special",
        pp: 30,
        power: Some(40),
        accuracy: Some(100),
    },
    Move {
        id: 85,
        name: "Thunderbolt",
        move_type: "Electric",
        category: "Special",
        pp: 15,
        power: Some(90),
        accuracy: Some(100),
    },
    Move {
        id: 86,
        name: "Thunder Wave",
        move_type: "Electric",
        category: "Status",
        pp: 20,
        power: None,
        accuracy: Some(90),
    },
    Move {
        id: 87,
        name: "Thunder",
        move_type: "Electric",
        category: "Special",
        pp: 10,
        power: Some(110),
        accuracy: Some(70),
    },
    Move {
        id: 88,
        name: "Rock Throw",
        move_type: "Rock",
        category: "Physical",
        pp: 15,
        power: Some(50),
        accuracy: Some(90),
    },
    Move {
        id: 89,
        name: "Earthquake",
        move_type: "Ground",
        category: "Physical",
        pp: 10,
        power: Some(100),
        accuracy: Some(100),
    },
    Move {
        id: 90,
        name: "Fissure",
        move_type: "Ground",
        category: "Physical",
        pp: 5,
        power: None,
        accuracy: Some(30),
    },
    Move {
        id: 91,
        name: "Dig",
        move_type: "Ground",
        category: "Physical",
        pp: 10,
        power: Some(80),
        accuracy: Some(100),
    },
    Move {
        id: 92,
        name: "Toxic",
        move_type: "Poison",
        category: "Status",
        pp: 10,
        power: None,
        accuracy: Some(90),
    },
    Move {
        id: 93,
        name: "Confusion",
        move_type: "Psychic",
        category: "Special",
        pp: 25,
        power: Some(50),
        accuracy: Some(100),
    },
    Move {
        id: 94,
        name: "Psychic",
        move_type: "Psychic",
        category: "Special",
        pp: 10,
        power: Some(90),
        accuracy: Some(100),
    },
    Move {
        id: 95,
        name: "Hypnosis",
        move_type: "Psychic",
        category: "Status",
        pp: 20,
        power: None,
        accuracy: Some(60),
    },
    Move {
        id: 96,
        name: "Meditate",
        move_type: "Psychic",
        category: "Status",
        pp: 40,
        power: None,
        accuracy: None,
    },
    Move {
        id: 97,
        name: "Agility",
        move_type: "Psychic",
        category: "Status",
        pp: 30,
        power: None,
        accuracy: None,
    },
    Move {
        id: 98,
        name: "Quick Attack",
        move_type: "Normal",
        category: "Physical",
        pp: 30,
        power: Some(40),
        accuracy: Some(100),
    },
    Move {
        id: 99,
        name: "Rage",
        move_type: "Normal",
        category: "Physical",
        pp: 20,
        power: Some(20),
        accuracy: Some(100),
    },
    Move {
        id: 100,
        name: "Teleport",
        move_type: "Psychic",
        category: "Status",
        pp: 20,
        power: None,
        accuracy: None,
    },
    Move {
        id: 101,
        name: "Night Shade",
        move_type: "Ghost",
        category: "Special",
        pp: 15,
        power: None,
        accuracy: Some(100),
    },
    Move {
        id: 102,
        name: "Mimic",
        move_type: "Normal",
        category: "Status",
        pp: 10,
        power: None,
        accuracy: None,
    },
    Move {
        id: 103,
        name: "Screech",
        move_type: "Normal",
        category: "Status",
        pp: 40,
        power: None,
        accuracy: Some(85),
    },
    Move {
        id: 104,
        name: "Double Team",
        move_type: "Normal",
        category: "Status",
        pp: 15,
        power: None,
        accuracy: None,
    },
    Move {
        id: 105,
        name: "Recover",
        move_type: "Normal",
        category: "Status",
        pp: 5,
        power: None,
        accuracy: None,
    },
    Move {
        id: 106,
        name: "Harden",
        move_type: "Normal",
        category: "Status",
        pp: 30,
        power: None,
        accuracy: None,
    },
    Move {
        id: 107,
        name: "Minimize",
        move_type: "Normal",
        category: "Status",
        pp: 10,
        power: None,
        accuracy: None,
    },
    Move {
        id: 108,
        name: "Smokescreen",
        move_type: "Normal",
        category: "Status",
        pp: 20,
        power: None,
        accuracy: Some(100),
    },
    Move {
        id: 109,
        name: "Confuse Ray",
        move_type: "Ghost",
        category: "Status",
        pp: 10,
        power: None,
        accuracy: Some(100),
    },
    Move {
        id: 110,
        name: "Withdraw",
        move_type: "Water",
        category: "Status",
        pp: 40,
        power: None,
        accuracy: None,
    },
    Move {
        id: 111,
        name: "Defense Curl",
        move_type: "Normal",
        category: "Status",
        pp: 40,
        power: None,
        accuracy: None,
    },
    Move {
        id: 112,
        name: "Barrier",
        move_type: "Psychic",
        category: "Status",
        pp: 20,
        power: None,
        accuracy: None,
    },
    Move {
        id: 113,
        name: "Light Screen",
        move_type: "Psychic",
        category: "Status",
        pp: 30,
        power: None,
        accuracy: None,
    },
    Move {
        id: 114,
        name: "Haze",
        move_type: "Ice",
        category: "Status",
        pp: 30,
        power: None,
        accuracy: None,
    },
    Move {
        id: 115,
        name: "Reflect",
        move_type: "Psychic",
        category: "Status",
        pp: 20,
        power: None,
        accuracy: None,
    },
    Move {
        id: 116,
        name: "Focus Energy",
        move_type: "Normal",
        category: "Status",
        pp: 30,
        power: None,
        accuracy: None,
    },
    Move {
        id: 117,
        name: "Bide",
        move_type: "Normal",
        category: "Physical",
        pp: 10,
        power: None,
        accuracy: None,
    },
    Move {
        id: 118,
        name: "Metronome",
        move_type: "Normal",
        category: "Status",
        pp: 10,
        power: None,
        accuracy: None,
    },
    Move {
        id: 119,
        name: "Mirror Move",
        move_type: "Flying",
        category: "Status",
        pp: 20,
        power: None,
        accuracy: None,
    },
    Move {
        id: 120,
        name: "Self-Destruct",
        move_type: "Normal",
        category: "Physical",
        pp: 5,
        power: Some(200),
        accuracy: Some(100),
    },
    Move {
        id: 121,
        name: "Egg Bomb",
        move_type: "Normal",
        category: "Physical",
        pp: 10,
        power: Some(100),
        accuracy: Some(75),
    },
    Move {
        id: 122,
        name: "Lick",
        move_type: "Ghost",
        category: "Physical",
        pp: 30,
        power: Some(30),
        accuracy: Some(100),
    },
    Move {
        id: 123,
        name: "Smog",
        move_type: "Poison",
        category: "Special",
        pp: 20,
        power: Some(30),
        accuracy: Some(70),
    },
    Move {
        id: 124,
        name: "Sludge",
        move_type: "Poison",
        category: "Special",
        pp: 20,
        power: Some(65),
        accuracy: Some(100),
    },
    Move {
        id: 125,
        name: "Bone Club",
        move_type: "Ground",
        category: "Physical",
        pp: 20,
        power: Some(65),
        accuracy: Some(85),
    },
    Move {
        id: 126,
        name: "Fire Blast",
        move_type: "Fire",
        category: "Special",
        pp: 5,
        power: Some(110),
        accuracy: Some(85),
    },
    Move {
        id: 127,
        name: "Waterfall",
        move_type: "Water",
        category: "Physical",
        pp: 15,
        power: Some(80),
        accuracy: Some(100),
    },
    Move {
        id: 128,
        name: "Clamp",
        move_type: "Water",
        category: "Physical",
        pp: 15,
        power: Some(35),
        accuracy: Some(85),
    },
    Move {
        id: 129,
        name: "Swift",
        move_type: "Normal",
        category: "Special",
        pp: 20,
        power: Some(60),
        accuracy: None,
    },
    Move {
        id: 130,
        name: "Skull Bash",
        move_type: "Normal",
        category: "Physical",
        pp: 10,
        power: Some(130),
        accuracy: Some(100),
    },
    Move {
        id: 131,
        name: "Spike Cannon",
        move_type: "Normal",
        category: "Physical",
        pp: 15,
        power: Some(20),
        accuracy: Some(100),
    },
    Move {
        id: 132,
        name: "Constrict",
        move_type: "Normal",
        category: "Physical",
        pp: 35,
        power: Some(10),
        accuracy: Some(100),
    },
    Move {
        id: 133,
        name: "Amnesia",
        move_type: "Psychic",
        category: "Status",
        pp: 20,
        power: None,
        accuracy: None,
    },
    Move {
        id: 134,
        name: "Kinesis",
        move_type: "Psychic",
        category: "Status",
        pp: 15,
        power: None,
        accuracy: Some(80),
    },
    Move {
        id: 135,
        name: "Soft-Boiled",
        move_type: "Normal",
        category: "Status",
        pp: 5,
        power: None,
        accuracy: None,
    },
    Move {
        id: 136,
        name: "High Jump Kick",
        move_type: "Fighting",
        category: "Physical",
        pp: 10,
        power: Some(130),
        accuracy: Some(90),
    },
    Move {
        id: 137,
        name: "Glare",
        move_type: "Normal",
        category: "Status",
        pp: 30,
        power: None,
        accuracy: Some(100),
    },
    Move {
        id: 138,
        name: "Dream Eater",
        move_type: "Psychic",
        category: "Special",
        pp: 15,
        power: Some(100),
        accuracy: Some(100),
    },
    Move {
        id: 139,
        name: "Poison Gas",
        move_type: "Poison",
        category: "Status",
        pp: 40,
        power: None,
        accuracy: Some(90),
    },
    Move {
        id: 140,
        name: "Barrage",
        move_type: "Normal",
        category: "Physical",
        pp: 20,
        power: Some(15),
        accuracy: Some(85),
    },
    Move {
        id: 141,
        name: "Leech Life",
        move_type: "Bug",
        category: "Physical",
        pp: 10,
        power: Some(80),
        accuracy: Some(100),
    },
    Move {
        id: 142,
        name: "Lovely Kiss",
        move_type: "Normal",
        category: "Status",
        pp: 10,
        power: None,
        accuracy: Some(75),
    },
    Move {
        id: 143,
        name: "Sky Attack",
        move_type: "Flying",
        category: "Physical",
        pp: 5,
        power: Some(140),
        accuracy: Some(90),
    },
    Move {
        id: 144,
        name: "Transform",
        move_type: "Normal",
        category: "Status",
        pp: 10,
        power: None,
        accuracy: None,
    },
    Move {
        id: 145,
        name: "Bubble",
        move_type: "Water",
        category: "Special",
        pp: 30,
        power: Some(40),
        accuracy: Some(100),
    },
    Move {
        id: 146,
        name: "Dizzy Punch",
        move_type: "Normal",
        category: "Physical",
        pp: 10,
        power: Some(70),
        accuracy: Some(100),
    },
    Move {
        id: 147,
        name: "Spore",
        move_type: "Grass",
        category: "Status",
        pp: 15,
        power: None,
        accuracy: Some(100),
    },
    Move {
        id: 148,
        name: "Flash",
        move_type: "Normal",
        category: "Status",
        pp: 20,
        power: None,
        accuracy: Some(100),
    },
    Move {
        id: 149,
        name: "Psywave",
        move_type: "Psychic",
        category: "Special",
        pp: 15,
        power: None,
        accuracy: Some(100),
    },
    Move {
        id: 150,
        name: "Splash",
        move_type: "Normal",
        category: "Status",
        pp: 40,
        power: None,
        accuracy: None,
    },
    Move {
        id: 151,
        name: "Acid Armor",
        move_type: "Poison",
        category: "Status",
        pp: 20,
        power: None,
        accuracy: None,
    },
    Move {
        id: 152,
        name: "Crabhammer",
        move_type: "Water",
        category: "Physical",
        pp: 10,
        power: Some(100),
        accuracy: Some(90),
    },
    Move {
        id: 153,
        name: "Explosion",
        move_type: "Normal",
        category: "Physical",
        pp: 5,
        power: Some(250),
        accuracy: Some(100),
    },
    Move {
        id: 154,
        name: "Fury Swipes",
        move_type: "Normal",
        category: "Physical",
        pp: 15,
        power: Some(18),
        accuracy: Some(80),
    },
    Move {
        id: 155,
        name: "Bonemerang",
        move_type: "Ground",
        category: "Physical",
        pp: 10,
        power: Some(50),
        accuracy: Some(90),
    },
    Move {
        id: 156,
        name: "Rest",
        move_type: "Psychic",
        category: "Status",
        pp: 5,
        power: None,
        accuracy: None,
    },
    Move {
        id: 157,
        name: "Rock Slide",
        move_type: "Rock",
        category: "Physical",
        pp: 10,
        power: Some(75),
        accuracy: Some(90),
    },
    Move {
        id: 158,
        name: "Hyper Fang",
        move_type: "Normal",
        category: "Physical",
        pp: 15,
        power: Some(80),
        accuracy: Some(90),
    },
    Move {
        id: 159,
        name: "Sharpen",
        move_type: "Normal",
        category: "Status",
        pp: 30,
        power: None,
        accuracy: None,
    },
    Move {
        id: 160,
        name: "Conversion",
        move_type: "Normal",
        category: "Status",
        pp: 30,
        power: None,
        accuracy: None,
    },
    Move {
        id: 161,
        name: "Tri Attack",
        move_type: "Normal",
        category: "Special",
        pp: 10,
        power: Some(80),
        accuracy: Some(100),
    },
    Move {
        id: 162,
        name: "Super Fang",
        move_type: "Normal",
        category: "Physical",
        pp: 10,
        power: None,
        accuracy: Some(90),
    },
    Move {
        id: 163,
        name: "Slash",
        move_type: "Normal",
        category: "Physical",
        pp: 20,
        power: Some(70),
        accuracy: Some(100),
    },
    Move {
        id: 164,
        name: "Substitute",
        move_type: "Normal",
        category: "Status",
        pp: 10,
        power: None,
        accuracy: None,
    },
    Move {
        id: 165,
        name: "Struggle",
        move_type: "Normal",
        category: "Physical",
        pp: 1,
        power: Some(50),
        accuracy: None,
    },
    Move {
        id: 166,
        name: "Sketch",
        move_type: "Normal",
        category: "Status",
        pp: 1,
        power: None,
        accuracy: None,
    },
    Move {
        id: 167,
        name: "Triple Kick",
        move_type: "Fighting",
        category: "Physical",
        pp: 10,
        power: Some(10),
        accuracy: Some(90),
    },
    Move {
        id: 168,
        name: "Thief",
        move_type: "Dark",
        category: "Physical",
        pp: 25,
        power: Some(60),
        accuracy: Some(100),
    },
    Move {
        id: 169,
        name: "Spider Web",
        move_type: "Bug",
        category: "Status",
        pp: 10,
        power: None,
        accuracy: None,
    },
    Move {
        id: 170,
        name: "Mind Reader",
        move_type: "Normal",
        category: "Status",
        pp: 5,
        power: None,
        accuracy: None,
    },
    Move {
        id: 171,
        name: "Nightmare",
        move_type: "Ghost",
        category: "Status",
        pp: 15,
        power: None,
        accuracy: Some(100),
    },
    Move {
        id: 172,
        name: "Flame Wheel",
        move_type: "Fire",
        category: "Physical",
        pp: 25,
        power: Some(60),
        accuracy: Some(100),
    },
    Move {
        id: 173,
        name: "Snore",
        move_type: "Normal",
        category: "Special",
        pp: 15,
        power: Some(50),
        accuracy: Some(100),
    },
    Move {
        id: 174,
        name: "Curse",
        move_type: "Ghost",
        category: "Status",
        pp: 10,
        power: None,
        accuracy: None,
    },
    Move {
        id: 175,
        name: "Flail",
        move_type: "Normal",
        category: "Physical",
        pp: 15,
        power: None,
        accuracy: Some(100),
    },
    Move {
        id: 176,
        name: "Conversion 2",
        move_type: "Normal",
        category: "Status",
        pp: 30,
        power: None,
        accuracy: None,
    },
    Move {
        id: 177,
        name: "Aeroblast",
        move_type: "Flying",
        category: "Special",
        pp: 5,
        power: Some(100),
        accuracy: Some(95),
    },
    Move {
        id: 178,
        name: "Cotton Spore",
        move_type: "Grass",
        category: "Status",
        pp: 40,
        power: None,
        accuracy: Some(100),
    },
    Move {
        id: 179,
        name: "Reversal",
        move_type: "Fighting",
        category: "Physical",
        pp: 15,
        power: None,
        accuracy: Some(100),
    },
    Move {
        id: 180,
        name: "Spite",
        move_type: "Ghost",
        category: "Status",
        pp: 10,
        power: None,
        accuracy: Some(100),
    },
    Move {
        id: 181,
        name: "Powder Snow",
        move_type: "Ice",
        category: "Special",
        pp: 25,
        power: Some(40),
        accuracy: Some(100),
    },
    Move {
        id: 182,
        name: "Protect",
        move_type: "Normal",
        category: "Status",
        pp: 10,
        power: None,
        accuracy: None,
    },
    Move {
        id: 183,
        name: "Mach Punch",
        move_type: "Fighting",
        category: "Physical",
        pp: 30,
        power: Some(40),
        accuracy: Some(100),
    },
    Move {
        id: 184,
        name: "Scary Face",
        move_type: "Normal",
        category: "Status",
        pp: 10,
        power: None,
        accuracy: Some(100),
    },
    Move {
        id: 185,
        name: "Feint Attack",
        move_type: "Dark",
        category: "Physical",
        pp: 20,
        power: Some(60),
        accuracy: None,
    },
    Move {
        id: 186,
        name: "Sweet Kiss",
        move_type: "Fairy",
        category: "Status",
        pp: 10,
        power: None,
        accuracy: Some(75),
    },
    Move {
        id: 187,
        name: "Belly Drum",
        move_type: "Normal",
        category: "Status",
        pp: 10,
        power: None,
        accuracy: None,
    },
    Move {
        id: 188,
        name: "Sludge Bomb",
        move_type: "Poison",
        category: "Special",
        pp: 10,
        power: Some(90),
        accuracy: Some(100),
    },
    Move {
        id: 189,
        name: "Mud-Slap",
        move_type: "Ground",
        category: "Special",
        pp: 10,
        power: Some(20),
        accuracy: Some(100),
    },
    Move {
        id: 190,
        name: "Octazooka",
        move_type: "Water",
        category: "Special",
        pp: 10,
        power: Some(65),
        accuracy: Some(85),
    },
    Move {
        id: 191,
        name: "Spikes",
        move_type: "Ground",
        category: "Status",
        pp: 20,
        power: None,
        accuracy: None,
    },
    Move {
        id: 192,
        name: "Zap Cannon",
        move_type: "Electric",
        category: "Special",
        pp: 5,
        power: Some(120),
        accuracy: Some(50),
    },
    Move {
        id: 193,
        name: "Foresight",
        move_type: "Normal",
        category: "Status",
        pp: 40,
        power: None,
        accuracy: None,
    },
    Move {
        id: 194,
        name: "Destiny Bond",
        move_type: "Ghost",
        category: "Status",
        pp: 5,
        power: None,
        accuracy: None,
    },
    Move {
        id: 195,
        name: "Perish Song",
        move_type: "Normal",
        category: "Status",
        pp: 5,
        power: None,
        accuracy: None,
    },
    Move {
        id: 196,
        name: "Icy Wind",
        move_type: "Ice",
        category: "Special",
        pp: 15,
        power: Some(55),
        accuracy: Some(95),
    },
    Move {
        id: 197,
        name: "Detect",
        move_type: "Fighting",
        category: "Status",
        pp: 5,
        power: None,
        accuracy: None,
    },
    Move {
        id: 198,
        name: "Bone Rush",
        move_type: "Ground",
        category: "Physical",
        pp: 10,
        power: Some(25),
        accuracy: Some(90),
    },
    Move {
        id: 199,
        name: "Lock-On",
        move_type: "Normal",
        category: "Status",
        pp: 5,
        power: None,
        accuracy: None,
    },
    Move {
        id: 200,
        name: "Outrage",
        move_type: "Dragon",
        category: "Physical",
        pp: 10,
        power: Some(120),
        accuracy: Some(100),
    },
    Move {
        id: 201,
        name: "Sandstorm",
        move_type: "Rock",
        category: "Status",
        pp: 10,
        power: None,
        accuracy: None,
    },
    Move {
        id: 202,
        name: "Giga Drain",
        move_type: "Grass",
        category: "Special",
        pp: 10,
        power: Some(75),
        accuracy: Some(100),
    },
    Move {
        id: 203,
        name: "Endure",
        move_type: "Normal",
        category: "Status",
        pp: 10,
        power: None,
        accuracy: None,
    },
    Move {
        id: 204,
        name: "Charm",
        move_type: "Fairy",
        category: "Status",
        pp: 20,
        power: None,
        accuracy: Some(100),
    },
    Move {
        id: 205,
        name: "Rollout",
        move_type: "Rock",
        category: "Physical",
        pp: 20,
        power: Some(30),
        accuracy: Some(90),
    },
    Move {
        id: 206,
        name: "False Swipe",
        move_type: "Normal",
        category: "Physical",
        pp: 40,
        power: Some(40),
        accuracy: Some(100),
    },
    Move {
        id: 207,
        name: "Swagger",
        move_type: "Normal",
        category: "Status",
        pp: 15,
        power: None,
        accuracy: Some(85),
    },
    Move {
        id: 208,
        name: "Milk Drink",
        move_type: "Normal",
        category: "Status",
        pp: 5,
        power: None,
        accuracy: None,
    },
    Move {
        id: 209,
        name: "Spark",
        move_type: "Electric",
        category: "Physical",
        pp: 20,
        power: Some(65),
        accuracy: Some(100),
    },
    Move {
        id: 210,
        name: "Fury Cutter",
        move_type: "Bug",
        category: "Physical",
        pp: 20,
        power: Some(40),
        accuracy: Some(95),
    },
    Move {
        id: 211,
        name: "Steel Wing",
        move_type: "Steel",
        category: "Physical",
        pp: 25,
        power: Some(70),
        accuracy: Some(90),
    },
    Move {
        id: 212,
        name: "Mean Look",
        move_type: "Normal",
        category: "Status",
        pp: 5,
        power: None,
        accuracy: None,
    },
    Move {
        id: 213,
        name: "Attract",
        move_type: "Normal",
        category: "Status",
        pp: 15,
        power: None,
        accuracy: Some(100),
    },
    Move {
        id: 214,
        name: "Sleep Talk",
        move_type: "Normal",
        category: "Status",
        pp: 10,
        power: None,
        accuracy: None,
    },
    Move {
        id: 215,
        name: "Heal Bell",
        move_type: "Normal",
        category: "Status",
        pp: 5,
        power: None,
        accuracy: None,
    },
    Move {
        id: 216,
        name: "Return",
        move_type: "Normal",
        category: "Physical",
        pp: 20,
        power: None,
        accuracy: Some(100),
    },
    Move {
        id: 217,
        name: "Present",
        move_type: "Normal",
        category: "Physical",
        pp: 15,
        power: None,
        accuracy: Some(90),
    },
    Move {
        id: 218,
        name: "Frustration",
        move_type: "Normal",
        category: "Physical",
        pp: 20,
        power: None,
        accuracy: Some(100),
    },
    Move {
        id: 219,
        name: "Safeguard",
        move_type: "Normal",
        category: "Status",
        pp: 25,
        power: None,
        accuracy: None,
    },
    Move {
        id: 220,
        name: "Pain Split",
        move_type: "Normal",
        category: "Status",
        pp: 20,
        power: None,
        accuracy: None,
    },
    Move {
        id: 221,
        name: "Sacred Fire",
        move_type: "Fire",
        category: "Physical",
        pp: 5,
        power: Some(100),
        accuracy: Some(95),
    },
    Move {
        id: 222,
        name: "Magnitude",
        move_type: "Ground",
        category: "Physical",
        pp: 30,
        power: None,
        accuracy: Some(100),
    },
    Move {
        id: 223,
        name: "Dynamic Punch",
        move_type: "Fighting",
        category: "Physical",
        pp: 5,
        power: Some(100),
        accuracy: Some(50),
    },
    Move {
        id: 224,
        name: "Megahorn",
        move_type: "Bug",
        category: "Physical",
        pp: 10,
        power: Some(120),
        accuracy: Some(85),
    },
    Move {
        id: 225,
        name: "Dragon Breath",
        move_type: "Dragon",
        category: "Special",
        pp: 20,
        power: Some(60),
        accuracy: Some(100),
    },
    Move {
        id: 226,
        name: "Baton Pass",
        move_type: "Normal",
        category: "Status",
        pp: 40,
        power: None,
        accuracy: None,
    },
    Move {
        id: 227,
        name: "Encore",
        move_type: "Normal",
        category: "Status",
        pp: 5,
        power: None,
        accuracy: Some(100),
    },
    Move {
        id: 228,
        name: "Pursuit",
        move_type: "Dark",
        category: "Physical",
        pp: 20,
        power: Some(40),
        accuracy: Some(100),
    },
    Move {
        id: 229,
        name: "Rapid Spin",
        move_type: "Normal",
        category: "Physical",
        pp: 40,
        power: Some(50),
        accuracy: Some(100),
    },
    Move {
        id: 230,
        name: "Sweet Scent",
        move_type: "Normal",
        category: "Status",
        pp: 20,
        power: None,
        accuracy: Some(100),
    },
    Move {
        id: 231,
        name: "Iron Tail",
        move_type: "Steel",
        category: "Physical",
        pp: 15,
        power: Some(100),
        accuracy: Some(75),
    },
    Move {
        id: 232,
        name: "Metal Claw",
        move_type: "Steel",
        category: "Physical",
        pp: 35,
        power: Some(50),
        accuracy: Some(95),
    },
    Move {
        id: 233,
        name: "Vital Throw",
        move_type: "Fighting",
        category: "Physical",
        pp: 10,
        power: Some(70),
        accuracy: None,
    },
    Move {
        id: 234,
        name: "Morning Sun",
        move_type: "Normal",
        category: "Status",
        pp: 5,
        power: None,
        accuracy: None,
    },
    Move {
        id: 235,
        name: "Synthesis",
        move_type: "Grass",
        category: "Status",
        pp: 5,
        power: None,
        accuracy: None,
    },
    Move {
        id: 236,
        name: "Moonlight",
        move_type: "Fairy",
        category: "Status",
        pp: 5,
        power: None,
        accuracy: None,
    },
    Move {
        id: 237,
        name: "Hidden Power",
        move_type: "Normal",
        category: "Special",
        pp: 15,
        power: Some(60),
        accuracy: Some(100),
    },
    Move {
        id: 238,
        name: "Cross Chop",
        move_type: "Fighting",
        category: "Physical",
        pp: 5,
        power: Some(100),
        accuracy: Some(80),
    },
    Move {
        id: 239,
        name: "Twister",
        move_type: "Dragon",
        category: "Special",
        pp: 20,
        power: Some(40),
        accuracy: Some(100),
    },
    Move {
        id: 240,
        name: "Rain Dance",
        move_type: "Water",
        category: "Status",
        pp: 5,
        power: None,
        accuracy: None,
    },
    Move {
        id: 241,
        name: "Sunny Day",
        move_type: "Fire",
        category: "Status",
        pp: 5,
        power: None,
        accuracy: None,
    },
    Move {
        id: 242,
        name: "Crunch",
        move_type: "Dark",
        category: "Physical",
        pp: 15,
        power: Some(80),
        accuracy: Some(100),
    },
    Move {
        id: 243,
        name: "Mirror Coat",
        move_type: "Psychic",
        category: "Special",
        pp: 20,
        power: None,
        accuracy: Some(100),
    },
    Move {
        id: 244,
        name: "Psych Up",
        move_type: "Normal",
        category: "Status",
        pp: 10,
        power: None,
        accuracy: None,
    },
    Move {
        id: 245,
        name: "Extreme Speed",
        move_type: "Normal",
        category: "Physical",
        pp: 5,
        power: Some(80),
        accuracy: Some(100),
    },
    Move {
        id: 246,
        name: "Ancient Power",
        move_type: "Rock",
        category: "Special",
        pp: 5,
        power: Some(60),
        accuracy: Some(100),
    },
    Move {
        id: 247,
        name: "Shadow Ball",
        move_type: "Ghost",
        category: "Special",
        pp: 15,
        power: Some(80),
        accuracy: Some(100),
    },
    Move {
        id: 248,
        name: "Future Sight",
        move_type: "Psychic",
        category: "Special",
        pp: 10,
        power: Some(120),
        accuracy: Some(100),
    },
    Move {
        id: 249,
        name: "Rock Smash",
        move_type: "Fighting",
        category: "Physical",
        pp: 15,
        power: Some(40),
        accuracy: Some(100),
    },
    Move {
        id: 250,
        name: "Whirlpool",
        move_type: "Water",
        category: "Special",
        pp: 15,
        power: Some(35),
        accuracy: Some(85),
    },
    Move {
        id: 251,
        name: "Beat Up",
        move_type: "Dark",
        category: "Physical",
        pp: 10,
        power: None,
        accuracy: Some(100),
    },
    Move {
        id: 252,
        name: "Fake Out",
        move_type: "Normal",
        category: "Physical",
        pp: 10,
        power: Some(40),
        accuracy: Some(100),
    },
    Move {
        id: 253,
        name: "Uproar",
        move_type: "Normal",
        category: "Special",
        pp: 10,
        power: Some(90),
        accuracy: Some(100),
    },
    Move {
        id: 254,
        name: "Stockpile",
        move_type: "Normal",
        category: "Status",
        pp: 20,
        power: None,
        accuracy: None,
    },
    Move {
        id: 255,
        name: "Spit Up",
        move_type: "Normal",
        category: "Special",
        pp: 10,
        power: None,
        accuracy: Some(100),
    },
    Move {
        id: 256,
        name: "Swallow",
        move_type: "Normal",
        category: "Status",
        pp: 10,
        power: None,
        accuracy: None,
    },
    Move {
        id: 257,
        name: "Heat Wave",
        move_type: "Fire",
        category: "Special",
        pp: 10,
        power: Some(95),
        accuracy: Some(90),
    },
    Move {
        id: 258,
        name: "Hail",
        move_type: "Ice",
        category: "Status",
        pp: 10,
        power: None,
        accuracy: None,
    },
    Move {
        id: 259,
        name: "Torment",
        move_type: "Dark",
        category: "Status",
        pp: 15,
        power: None,
        accuracy: Some(100),
    },
    Move {
        id: 260,
        name: "Flatter",
        move_type: "Dark",
        category: "Status",
        pp: 15,
        power: None,
        accuracy: Some(100),
    },
    Move {
        id: 261,
        name: "Will-O-Wisp",
        move_type: "Fire",
        category: "Status",
        pp: 15,
        power: None,
        accuracy: Some(85),
    },
    Move {
        id: 262,
        name: "Memento",
        move_type: "Dark",
        category: "Status",
        pp: 10,
        power: None,
        accuracy: Some(100),
    },
    Move {
        id: 263,
        name: "Facade",
        move_type: "Normal",
        category: "Physical",
        pp: 20,
        power: Some(70),
        accuracy: Some(100),
    },
    Move {
        id: 264,
        name: "Focus Punch",
        move_type: "Fighting",
        category: "Physical",
        pp: 20,
        power: Some(150),
        accuracy: Some(100),
    },
    Move {
        id: 265,
        name: "Smelling Salts",
        move_type: "Normal",
        category: "Physical",
        pp: 10,
        power: Some(70),
        accuracy: Some(100),
    },
    Move {
        id: 266,
        name: "Follow Me",
        move_type: "Normal",
        category: "Status",
        pp: 20,
        power: None,
        accuracy: None,
    },
    Move {
        id: 267,
        name: "Nature Power",
        move_type: "Normal",
        category: "Status",
        pp: 20,
        power: None,
        accuracy: None,
    },
    Move {
        id: 268,
        name: "Charge",
        move_type: "Electric",
        category: "Status",
        pp: 20,
        power: None,
        accuracy: None,
    },
    Move {
        id: 269,
        name: "Taunt",
        move_type: "Dark",
        category: "Status",
        pp: 20,
        power: None,
        accuracy: Some(100),
    },
    Move {
        id: 270,
        name: "Helping Hand",
        move_type: "Normal",
        category: "Status",
        pp: 20,
        power: None,
        accuracy: None,
    },
    Move {
        id: 271,
        name: "Trick",
        move_type: "Psychic",
        category: "Status",
        pp: 10,
        power: None,
        accuracy: Some(100),
    },
    Move {
        id: 272,
        name: "Role Play",
        move_type: "Psychic",
        category: "Status",
        pp: 10,
        power: None,
        accuracy: None,
    },
    Move {
        id: 273,
        name: "Wish",
        move_type: "Normal",
        category: "Status",
        pp: 10,
        power: None,
        accuracy: None,
    },
    Move {
        id: 274,
        name: "Assist",
        move_type: "Normal",
        category: "Status",
        pp: 20,
        power: None,
        accuracy: None,
    },
    Move {
        id: 275,
        name: "Ingrain",
        move_type: "Grass",
        category: "Status",
        pp: 20,
        power: None,
        accuracy: None,
    },
    Move {
        id: 276,
        name: "Superpower",
        move_type: "Fighting",
        category: "Physical",
        pp: 5,
        power: Some(120),
        accuracy: Some(100),
    },
    Move {
        id: 277,
        name: "Magic Coat",
        move_type: "Psychic",
        category: "Status",
        pp: 15,
        power: None,
        accuracy: None,
    },
    Move {
        id: 278,
        name: "Recycle",
        move_type: "Normal",
        category: "Status",
        pp: 10,
        power: None,
        accuracy: None,
    },
    Move {
        id: 279,
        name: "Revenge",
        move_type: "Fighting",
        category: "Physical",
        pp: 10,
        power: Some(60),
        accuracy: Some(100),
    },
    Move {
        id: 280,
        name: "Brick Break",
        move_type: "Fighting",
        category: "Physical",
        pp: 15,
        power: Some(75),
        accuracy: Some(100),
    },
    Move {
        id: 281,
        name: "Yawn",
        move_type: "Normal",
        category: "Status",
        pp: 10,
        power: None,
        accuracy: None,
    },
    Move {
        id: 282,
        name: "Knock Off",
        move_type: "Dark",
        category: "Physical",
        pp: 20,
        power: Some(65),
        accuracy: Some(100),
    },
    Move {
        id: 283,
        name: "Endeavor",
        move_type: "Normal",
        category: "Physical",
        pp: 5,
        power: None,
        accuracy: Some(100),
    },
    Move {
        id: 284,
        name: "Eruption",
        move_type: "Fire",
        category: "Special",
        pp: 5,
        power: Some(150),
        accuracy: Some(100),
    },
    Move {
        id: 285,
        name: "Skill Swap",
        move_type: "Psychic",
        category: "Status",
        pp: 10,
        power: None,
        accuracy: None,
    },
    Move {
        id: 286,
        name: "Imprison",
        move_type: "Psychic",
        category: "Status",
        pp: 10,
        power: None,
        accuracy: None,
    },
    Move {
        id: 287,
        name: "Refresh",
        move_type: "Normal",
        category: "Status",
        pp: 20,
        power: None,
        accuracy: None,
    },
    Move {
        id: 288,
        name: "Grudge",
        move_type: "Ghost",
        category: "Status",
        pp: 5,
        power: None,
        accuracy: None,
    },
    Move {
        id: 289,
        name: "Snatch",
        move_type: "Dark",
        category: "Status",
        pp: 10,
        power: None,
        accuracy: None,
    },
    Move {
        id: 290,
        name: "Secret Power",
        move_type: "Normal",
        category: "Physical",
        pp: 20,
        power: Some(70),
        accuracy: Some(100),
    },
    Move {
        id: 291,
        name: "Dive",
        move_type: "Water",
        category: "Physical",
        pp: 10,
        power: Some(80),
        accuracy: Some(100),
    },
    Move {
        id: 292,
        name: "Arm Thrust",
        move_type: "Fighting",
        category: "Physical",
        pp: 20,
        power: Some(15),
        accuracy: Some(100),
    },
    Move {
        id: 293,
        name: "Camouflage",
        move_type: "Normal",
        category: "Status",
        pp: 20,
        power: None,
        accuracy: None,
    },
    Move {
        id: 294,
        name: "Tail Glow",
        move_type: "Bug",
        category: "Status",
        pp: 20,
        power: None,
        accuracy: None,
    },
    Move {
        id: 295,
        name: "Luster Purge",
        move_type: "Psychic",
        category: "Special",
        pp: 5,
        power: Some(95),
        accuracy: Some(100),
    },
    Move {
        id: 296,
        name: "Mist Ball",
        move_type: "Psychic",
        category: "Special",
        pp: 5,
        power: Some(95),
        accuracy: Some(100),
    },
    Move {
        id: 297,
        name: "Feather Dance",
        move_type: "Flying",
        category: "Status",
        pp: 15,
        power: None,
        accuracy: Some(100),
    },
    Move {
        id: 298,
        name: "Teeter Dance",
        move_type: "Normal",
        category: "Status",
        pp: 20,
        power: None,
        accuracy: Some(100),
    },
    Move {
        id: 299,
        name: "Blaze Kick",
        move_type: "Fire",
        category: "Physical",
        pp: 10,
        power: Some(85),
        accuracy: Some(90),
    },
    Move {
        id: 300,
        name: "Mud Sport",
        move_type: "Ground",
        category: "Status",
        pp: 15,
        power: None,
        accuracy: None,
    },
    Move {
        id: 301,
        name: "Ice Ball",
        move_type: "Ice",
        category: "Physical",
        pp: 20,
        power: Some(30),
        accuracy: Some(90),
    },
    Move {
        id: 302,
        name: "Needle Arm",
        move_type: "Grass",
        category: "Physical",
        pp: 15,
        power: Some(60),
        accuracy: Some(100),
    },
    Move {
        id: 303,
        name: "Slack Off",
        move_type: "Normal",
        category: "Status",
        pp: 5,
        power: None,
        accuracy: None,
    },
    Move {
        id: 304,
        name: "Hyper Voice",
        move_type: "Normal",
        category: "Special",
        pp: 10,
        power: Some(90),
        accuracy: Some(100),
    },
    Move {
        id: 305,
        name: "Poison Fang",
        move_type: "Poison",
        category: "Physical",
        pp: 15,
        power: Some(50),
        accuracy: Some(100),
    },
    Move {
        id: 306,
        name: "Crush Claw",
        move_type: "Normal",
        category: "Physical",
        pp: 10,
        power: Some(75),
        accuracy: Some(95),
    },
    Move {
        id: 307,
        name: "Blast Burn",
        move_type: "Fire",
        category: "Special",
        pp: 5,
        power: Some(150),
        accuracy: Some(90),
    },
    Move {
        id: 308,
        name: "Hydro Cannon",
        move_type: "Water",
        category: "Special",
        pp: 5,
        power: Some(150),
        accuracy: Some(90),
    },
    Move {
        id: 309,
        name: "Meteor Mash",
        move_type: "Steel",
        category: "Physical",
        pp: 10,
        power: Some(90),
        accuracy: Some(90),
    },
    Move {
        id: 310,
        name: "Astonish",
        move_type: "Ghost",
        category: "Physical",
        pp: 15,
        power: Some(30),
        accuracy: Some(100),
    },
    Move {
        id: 311,
        name: "Weather Ball",
        move_type: "Normal",
        category: "Special",
        pp: 10,
        power: Some(50),
        accuracy: Some(100),
    },
    Move {
        id: 312,
        name: "Aromatherapy",
        move_type: "Grass",
        category: "Status",
        pp: 5,
        power: None,
        accuracy: None,
    },
    Move {
        id: 313,
        name: "Fake Tears",
        move_type: "Dark",
        category: "Status",
        pp: 20,
        power: None,
        accuracy: Some(100),
    },
    Move {
        id: 314,
        name: "Air Cutter",
        move_type: "Flying",
        category: "Special",
        pp: 25,
        power: Some(60),
        accuracy: Some(95),
    },
    Move {
        id: 315,
        name: "Overheat",
        move_type: "Fire",
        category: "Special",
        pp: 5,
        power: Some(130),
        accuracy: Some(90),
    },
    Move {
        id: 316,
        name: "Odor Sleuth",
        move_type: "Normal",
        category: "Status",
        pp: 40,
        power: None,
        accuracy: None,
    },
    Move {
        id: 317,
        name: "Rock Tomb",
        move_type: "Rock",
        category: "Physical",
        pp: 15,
        power: Some(60),
        accuracy: Some(95),
    },
    Move {
        id: 318,
        name: "Silver Wind",
        move_type: "Bug",
        category: "Special",
        pp: 5,
        power: Some(60),
        accuracy: Some(100),
    },
    Move {
        id: 319,
        name: "Metal Sound",
        move_type: "Steel",
        category: "Status",
        pp: 40,
        power: None,
        accuracy: Some(85),
    },
    Move {
        id: 320,
        name: "Grass Whistle",
        move_type: "Grass",
        category: "Status",
        pp: 15,
        power: None,
        accuracy: Some(55),
    },
    Move {
        id: 321,
        name: "Tickle",
        move_type: "Normal",
        category: "Status",
        pp: 20,
        power: None,
        accuracy: Some(100),
    },
    Move {
        id: 322,
        name: "Cosmic Power",
        move_type: "Psychic",
        category: "Status",
        pp: 20,
        power: None,
        accuracy: None,
    },
    Move {
        id: 323,
        name: "Water Spout",
        move_type: "Water",
        category: "Special",
        pp: 5,
        power: Some(150),
        accuracy: Some(100),
    },
    Move {
        id: 324,
        name: "Signal Beam",
        move_type: "Bug",
        category: "Special",
        pp: 15,
        power: Some(75),
        accuracy: Some(100),
    },
    Move {
        id: 325,
        name: "Shadow Punch",
        move_type: "Ghost",
        category: "Physical",
        pp: 20,
        power: Some(60),
        accuracy: None,
    },
    Move {
        id: 326,
        name: "Extrasensory",
        move_type: "Psychic",
        category: "Special",
        pp: 20,
        power: Some(80),
        accuracy: Some(100),
    },
    Move {
        id: 327,
        name: "Sky Uppercut",
        move_type: "Fighting",
        category: "Physical",
        pp: 15,
        power: Some(85),
        accuracy: Some(90),
    },
    Move {
        id: 328,
        name: "Sand Tomb",
        move_type: "Ground",
        category: "Physical",
        pp: 15,
        power: Some(35),
        accuracy: Some(85),
    },
    Move {
        id: 329,
        name: "Sheer Cold",
        move_type: "Ice",
        category: "Special",
        pp: 5,
        power: None,
        accuracy: Some(30),
    },
    Move {
        id: 330,
        name: "Muddy Water",
        move_type: "Water",
        category: "Special",
        pp: 10,
        power: Some(90),
        accuracy: Some(85),
    },
    Move {
        id: 331,
        name: "Bullet Seed",
        move_type: "Grass",
        category: "Physical",
        pp: 30,
        power: Some(25),
        accuracy: Some(100),
    },
    Move {
        id: 332,
        name: "Aerial Ace",
        move_type: "Flying",
        category: "Physical",
        pp: 20,
        power: Some(60),
        accuracy: None,
    },
    Move {
        id: 333,
        name: "Icicle Spear",
        move_type: "Ice",
        category: "Physical",
        pp: 30,
        power: Some(25),
        accuracy: Some(100),
    },
    Move {
        id: 334,
        name: "Iron Defense",
        move_type: "Steel",
        category: "Status",
        pp: 15,
        power: None,
        accuracy: None,
    },
    Move {
        id: 335,
        name: "Block",
        move_type: "Normal",
        category: "Status",
        pp: 5,
        power: None,
        accuracy: None,
    },
    Move {
        id: 336,
        name: "Howl",
        move_type: "Normal",
        category: "Status",
        pp: 40,
        power: None,
        accuracy: None,
    },
    Move {
        id: 337,
        name: "Dragon Claw",
        move_type: "Dragon",
        category: "Physical",
        pp: 15,
        power: Some(80),
        accuracy: Some(100),
    },
    Move {
        id: 338,
        name: "Frenzy Plant",
        move_type: "Grass",
        category: "Special",
        pp: 5,
        power: Some(150),
        accuracy: Some(90),
    },
    Move {
        id: 339,
        name: "Bulk Up",
        move_type: "Fighting",
        category: "Status",
        pp: 20,
        power: None,
        accuracy: None,
    },
    Move {
        id: 340,
        name: "Bounce",
        move_type: "Flying",
        category: "Physical",
        pp: 5,
        power: Some(85),
        accuracy: Some(85),
    },
    Move {
        id: 341,
        name: "Mud Shot",
        move_type: "Ground",
        category: "Special",
        pp: 15,
        power: Some(55),
        accuracy: Some(95),
    },
    Move {
        id: 342,
        name: "Poison Tail",
        move_type: "Poison",
        category: "Physical",
        pp: 25,
        power: Some(50),
        accuracy: Some(100),
    },
    Move {
        id: 343,
        name: "Covet",
        move_type: "Normal",
        category: "Physical",
        pp: 25,
        power: Some(60),
        accuracy: Some(100),
    },
    Move {
        id: 344,
        name: "Volt Tackle",
        move_type: "Electric",
        category: "Physical",
        pp: 15,
        power: Some(120),
        accuracy: Some(100),
    },
    Move {
        id: 345,
        name: "Magical Leaf",
        move_type: "Grass",
        category: "Special",
        pp: 20,
        power: Some(60),
        accuracy: None,
    },
    Move {
        id: 346,
        name: "Water Sport",
        move_type: "Water",
        category: "Status",
        pp: 15,
        power: None,
        accuracy: None,
    },
    Move {
        id: 347,
        name: "Calm Mind",
        move_type: "Psychic",
        category: "Status",
        pp: 20,
        power: None,
        accuracy: None,
    },
    Move {
        id: 348,
        name: "Leaf Blade",
        move_type: "Grass",
        category: "Physical",
        pp: 15,
        power: Some(90),
        accuracy: Some(100),
    },
    Move {
        id: 349,
        name: "Dragon Dance",
        move_type: "Dragon",
        category: "Status",
        pp: 20,
        power: None,
        accuracy: None,
    },
    Move {
        id: 350,
        name: "Rock Blast",
        move_type: "Rock",
        category: "Physical",
        pp: 10,
        power: Some(25),
        accuracy: Some(90),
    },
    Move {
        id: 351,
        name: "Shock Wave",
        move_type: "Electric",
        category: "Special",
        pp: 20,
        power: Some(60),
        accuracy: None,
    },
    Move {
        id: 352,
        name: "Water Pulse",
        move_type: "Water",
        category: "Special",
        pp: 20,
        power: Some(60),
        accuracy: Some(100),
    },
    Move {
        id: 353,
        name: "Doom Desire",
        move_type: "Steel",
        category: "Special",
        pp: 5,
        power: Some(140),
        accuracy: Some(100),
    },
    Move {
        id: 354,
        name: "Psycho Boost",
        move_type: "Psychic",
        category: "Special",
        pp: 5,
        power: Some(140),
        accuracy: Some(90),
    },
];

pub fn get_move_by_id(id: u16) -> Option<Move> {
    info!("move id {}", id);
    MOVES.iter().find(|m| m.id == id).cloned()
}
